version: '3.8'

services:
  awsmapdb:
    env_file: ".env"
    image: neo4j:5.20.0-enterprise 
    container_name: awsmapdb
#    ports:
#      - "7474:7474"
#      - "7687:7687"
    volumes:
      - ./data:/data
      - ./plugins:/plugins
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_server_default__advertised__address=${NEO4J_HOST}
      - NEO4J_server_default__listen__address=${NEO4J_HOST}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_bolt_advertised__address=${NEO4J_HOST}:7687
      - NEO4J_server_http_advertised__address=${NEO4J_HOST}:7474
      - NEO4J_dbms_usage__report_enabled=false 
      - NEO4J_server_config_strict__validation_enabled=false
    restart: always
    network_mode: host
